#pragma once


/*
		tahmlib
		A C++ library for Game Development

		Author: Tamta Asatiani
		tamta@geolab.edu.ge

		-- Keys --

		Definitions for all audio and sound related methods.
*/





// event keys

enum Keys
{
	KEY_RETURN = SDLK_RETURN,
	KEY_ESCAPE = SDLK_ESCAPE,
	KEY_BACKSPACE = SDLK_BACKSPACE,
	KEY_TAB = SDLK_TAB,
	KEY_SPACE = SDLK_SPACE,

	KEY_0 = SDLK_0,
	KEY_1 = SDLK_1,
	KEY_2 = SDLK_2,
	KEY_3 = SDLK_3,
	KEY_4 = SDLK_4,
	KEY_5 = SDLK_5,
	KEY_6 = SDLK_6,
	KEY_7 = SDLK_7,
	KEY_8 = SDLK_8,
	KEY_9 = SDLK_9,

	KEY_A = SDLK_a,
	KEY_B = SDLK_b,
	KEY_C = SDLK_c,
	KEY_D = SDLK_d,
	KEY_E = SDLK_e,
	KEY_F = SDLK_f,
	KEY_G = SDLK_g,
	KEY_H = SDLK_h,
	KEY_I = SDLK_i,
	KEY_J = SDLK_j,
	KEY_K = SDLK_k,
	KEY_L = SDLK_l,
	KEY_M = SDLK_m,
	KEY_N = SDLK_n,
	KEY_O = SDLK_o,
	KEY_P = SDLK_p,
	KEY_Q = SDLK_q,
	KEY_R = SDLK_r,
	KEY_S = SDLK_s,
	KEY_T = SDLK_t,
	KEY_U = SDLK_u,
	KEY_V = SDLK_v,
	KEY_W = SDLK_w,
	KEY_X = SDLK_x,
	KEY_Y = SDLK_y,
	KEY_Z = SDLK_z
};

// keycodes for keyboard state

enum KeyCodes {

	KEYCODE_RETURN = SDL_SCANCODE_RETURN,
	KEYCODE_ESCAPE = SDL_SCANCODE_ESCAPE,
	KEYCODE_BACKSPACE = SDL_SCANCODE_BACKSPACE,
	KEYCODE_TAB = SDL_SCANCODE_TAB,
	KEYCODE_SPACE = SDL_SCANCODE_SPACE,


	KEYCODE_A = SDL_SCANCODE_A,
	KEYCODE_B = SDL_SCANCODE_B,
	KEYCODE_C = SDL_SCANCODE_C,
	KEYCODE_D = SDL_SCANCODE_D,
	KEYCODE_E = SDL_SCANCODE_E,
	KEYCODE_F = SDL_SCANCODE_F,
	KEYCODE_G = SDL_SCANCODE_G,
	KEYCODE_H = SDL_SCANCODE_H,
	KEYCODE_I = SDL_SCANCODE_I,
	KEYCODE_J = SDL_SCANCODE_J,
	KEYCODE_K = SDL_SCANCODE_K,
	KEYCODE_L = SDL_SCANCODE_L,
	KEYCODE_M = SDL_SCANCODE_M,
	KEYCODE_N = SDL_SCANCODE_N,
	KEYCODE_O = SDL_SCANCODE_O,
	KEYCODE_P = SDL_SCANCODE_P,
	KEYCODE_Q = SDL_SCANCODE_Q,
	KEYCODE_R = SDL_SCANCODE_R,
	KEYCODE_S = SDL_SCANCODE_S,
	KEYCODE_T = SDL_SCANCODE_T,
	KEYCODE_U = SDL_SCANCODE_U,
	KEYCODE_V = SDL_SCANCODE_V,
	KEYCODE_W = SDL_SCANCODE_W,
	KEYCODE_X = SDL_SCANCODE_X,
	KEYCODE_Y = SDL_SCANCODE_Y,
	KEYCODE_Z = SDL_SCANCODE_Z,


	KEYCODE_0 = SDL_SCANCODE_0,
	KEYCODE_1 = SDL_SCANCODE_1,
	KEYCODE_2 = SDL_SCANCODE_2,
	KEYCODE_3 = SDL_SCANCODE_3,
	KEYCODE_4 = SDL_SCANCODE_4,
	KEYCODE_5 = SDL_SCANCODE_5,
	KEYCODE_6 = SDL_SCANCODE_6,
	KEYCODE_7 = SDL_SCANCODE_7,
	KEYCODE_8 = SDL_SCANCODE_8,
	KEYCODE_9 = SDL_SCANCODE_0,


	KEYCODE_RIGHT = SDL_SCANCODE_RIGHT,
	KEYCODE_LEFT = SDL_SCANCODE_LEFT,
	KEYCODE_DOWN = SDL_SCANCODE_DOWN,
	KEYCODE_UP = SDL_SCANCODE_UP
};